### ISSUE TITLE
Blended items not working as-is

### ISSUE THREAD

**Issue by Imamadmad** [WestpacCXTeam/blender#1]
Hi guys,

This might be the wrong repo to raise this, but it's not clear what the right one is.

I've been using the blender to make a small web app for an internal team, but it seems the blends don't have enough information in them to work right out of the box. For example, using the tabs, they don't open and close straight after blending, and the alerts don't include the icons as dependencies (and even once blended again with the icons, they don't seem to be showing up). Could either a) all dependencies be blended with each section so that they work out of the box or b) each module lists all the required code needed to run said module?

Thanks!

**Comment by jonnystening** [comment]
Closing as dup of https://github.com/WestpacCXTeam/GUI-source/issues/368
